-- ============================================================
-- 001_add_foreign_keys.sql — MANUAL HANA EXECUTION ONLY
-- ============================================================
-- This script adds FK constraints for referential integrity.
--
-- IMPORTANT: This file is NOT automatically run by CAP deploy
-- or the HDI container. In HANA, FK constraints are managed
-- by .hdbconstraint artifacts generated by:
--   cds build --production   (produces db/src/gen/ artifacts)
-- Only run this manually in scenarios where HDI-generated
-- constraints are not in use.
-- ============================================================

ALTER TABLE SAP_Java_Personal_Accounts_cds_Books
  ADD CONSTRAINT FK_BOOKS_AUTHOR
  FOREIGN KEY (author_ID)
  REFERENCES SAP_Java_Personal_Accounts_cds_Authors(ID);

ALTER TABLE SAP_Java_Personal_Accounts_cds_Books
  ADD CONSTRAINT FK_BOOKS_GENRE
  FOREIGN KEY (genre_ID)
  REFERENCES SAP_Java_Personal_Accounts_cds_Genres(ID);

ALTER TABLE SAP_Java_Personal_Accounts_cds_Loans
  ADD CONSTRAINT FK_LOANS_BOOK
  FOREIGN KEY (book_ID)
  REFERENCES SAP_Java_Personal_Accounts_cds_Books(ID);

ALTER TABLE SAP_Java_Personal_Accounts_cds_Loans
  ADD CONSTRAINT FK_LOANS_MEMBER
  FOREIGN KEY (member_ID)
  REFERENCES SAP_Java_Personal_Accounts_cds_Members(ID);
